# ==============================================================================
# Automated Installer for Donated Medicine Manager (HOSxP Integration)
# โรงพยาบาลสมเด็จพระยุพราชสายบุรี (รหัสหน่วยงาน: 10690)
# รองรับ Windows Server / Windows 10 & 11 (PowerShell 5.1 & PowerShell 7+)
# ==============================================================================

param (
    [string]$HosxpHost = "192.168.0.251",
    [string]$HosxpPort = "3306",
    [string]$HosxpUser = "sa",
    [string]$HosxpPassword = "",
    [string]$HosxpDb = "hos",
    [string]$HospitalCode = "10690",
    [string]$HospitalName = "โรงพยาบาลสมเด็จพระยุพราชสายบุรี",
    [int]$FrontendPort = 80,
    [int]$BackendPort = 8000
)

$ErrorActionPreference = "Stop"
$ProjectDir = $PSScriptRoot

function Write-Step([string]$msg) { Write-Host "`n[INSTALL] $msg" -ForegroundColor Cyan }
function Write-OK([string]$msg)   { Write-Host "  + $msg" -ForegroundColor Green }
function Write-Warn([string]$msg) { Write-Host "  ! $msg" -ForegroundColor Yellow }
function Write-Fail([string]$msg) { Write-Host "  X $msg" -ForegroundColor Red; exit 1 }

Write-Host "=====================================================================" -ForegroundColor Green
Write-Host "   ระบบบริหารจัดการคลังยาบริจาค - OPD Pharmacy Server Installer" -ForegroundColor Green
Write-Host "   โรงพยาบาลสมเด็จพระยุพราชสายบุรี (เชื่อมต่อฐานข้อมูล HOSxP)" -ForegroundColor Green
Write-Host "=====================================================================" -ForegroundColor Green

# STEP 1: Check Prerequisites
Write-Step "1/8 ตรวจสอบความพร้อมของระบบ (Prerequisites)..."
try { 
    $v = docker --version 2>&1
    Write-OK "Docker: $v" 
} catch { 
    Write-Fail "ไม่พบ Docker กรุณาติดตั้ง Docker Desktop จาก https://www.docker.com ก่อนดำเนินการ" 
}

try { 
    $v = docker compose version 2>&1
    Write-OK "Docker Compose: $v" 
} catch { 
    Write-Fail "ไม่พบ Docker Compose กรุณาอัปเดต Docker Desktop" 
}

try { 
    docker info > $null 2>&1
    Write-OK "Docker daemon กำลังทำงานปกติ" 
} catch { 
    Write-Fail "Docker daemon ยังไม่เริ่มทำงาน กรุณาเปิดโปรแกรม Docker Desktop ก่อน" 
}

# STEP 2: Collect Configuration
Write-Step "2/8 กำหนดค่าการเชื่อมต่อฐานข้อมูล HOSxP MySQL..."
$inputHost = Read-Host "  IP Server HOSxP MySQL [Enter เพื่อใช้: $HosxpHost]"
if ($inputHost.Trim()) { $HosxpHost = $inputHost.Trim() }

$inputPort = Read-Host "  Port HOSxP MySQL [Enter เพื่อใช้: $HosxpPort]"
if ($inputPort.Trim()) { $HosxpPort = $inputPort.Trim() }

$inputUser = Read-Host "  User HOSxP MySQL [Enter เพื่อใช้: $HosxpUser]"
if ($inputUser.Trim()) { $HosxpUser = $inputUser.Trim() }

if (-not $HosxpPassword) {
    $inputPass = Read-Host "  Password HOSxP MySQL for '$HosxpUser' [Enter เพื่อใช้: sa]"
    if ($inputPass) { $HosxpPassword = $inputPass } else { $HosxpPassword = "sa" }
}

$inputDb = Read-Host "  Database Name [Enter เพื่อใช้: $HosxpDb]"
if ($inputDb.Trim()) { $HosxpDb = $inputDb.Trim() }

# STEP 3: Write .env
Write-Step "3/8 สร้างและบันทึกไฟล์ .env..."
$envFile = Join-Path $ProjectDir ".env"
$dbUrl = "mysql+pymysql://${HosxpUser}:${HosxpPassword}@${HosxpHost}:${HosxpPort}/${HosxpDb}"
@"
# Auto-generated by install.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
DATABASE_URL=$dbUrl
HOSXP_HOST=$HosxpHost
HOSXP_PORT=$HosxpPort
HOSXP_USER=$HosxpUser
HOSXP_PASSWORD=$HosxpPassword
HOSXP_DB=$HosxpDb
HOSPITAL_CODE=$HospitalCode
HOSPITAL_NAME=$HospitalName
FRONTEND_PORT=$FrontendPort
BACKEND_PORT=$BackendPort
"@ | Out-File -FilePath $envFile -Encoding UTF8 -Force
Write-OK "บันทึกไฟล์ .env เรียบร้อยแล้ว"

# STEP 4: Write secrets.toml
Write-Step "4/8 สร้างและบันทึกไฟล์ secrets.toml..."
$secretsFile = Join-Path $ProjectDir "secrets.toml"
@"
# Auto-generated by install.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
[database]
host = "$HosxpHost"
port = $HosxpPort
name = "$HosxpDb"
user = "$HosxpUser"
password = "$HosxpPassword"
driver = "mysql+pymysql"
url = "$dbUrl"

[system]
hospital_name = "$HospitalName"
hospital_code = "$HospitalCode"
environment = "production"
"@ | Out-File -FilePath $secretsFile -Encoding UTF8 -Force
Write-OK "บันทึกไฟล์ secrets.toml เรียบร้อยแล้ว"

# STEP 5: Build images
Write-Step "5/8 คอมไพล์ Docker Images (backend & frontend)..."
Set-Location $ProjectDir
docker compose build
Write-OK "Build Docker Images สำเร็จ"

# STEP 6: Start services
Write-Step "6/8 สั่งรันบริการด้วย Docker Compose..."
docker compose up -d
Write-OK "Containers เริ่มทำงานเรียบร้อยแล้ว"

# STEP 7: Verify health
Write-Step "7/8 ตรวจสอบความพร้อมของระบบ (Health Check)..."
Start-Sleep 8
try {
    $h = Invoke-RestMethod "http://localhost:${BackendPort}/healthz" -TimeoutSec 15
    Write-OK "Backend API Status: $($h.status)"
    $r = Invoke-RestMethod "http://localhost:${BackendPort}/readyz" -TimeoutSec 15
    Write-OK "Database Connection: $($r.database)"
} catch { 
    Write-Warn "ระบบกำลังเริ่มต้นการทำงาน หรือกำลังเชื่อมต่อฐานข้อมูล HOSxP..." 
}

# STEP 8: Firewall & Auto-start setup
Write-Step "8/8 ตั้งค่า Windows Firewall และ Auto-start..."
try {
    New-NetFirewallRule -DisplayName "Donated-Medicine-Web-$FrontendPort" `
        -Direction Inbound -Protocol TCP -LocalPort $FrontendPort -Action Allow -EA SilentlyContinue | Out-Null
    New-NetFirewallRule -DisplayName "Donated-Medicine-API-$BackendPort" `
        -Direction Inbound -Protocol TCP -LocalPort $BackendPort -Action Allow -EA SilentlyContinue | Out-Null
    Write-OK "เปิดพอร์ต Firewall $FrontendPort (Web) และ $BackendPort (API) เรียบร้อยแล้ว"
} catch {
    Write-Warn "ไม่สามารถเพิ่มกฎ Firewall อัตโนมัติได้ (ต้องเปิด PowerShell ด้วย Run as Administrator)"
}

# Get Local IP
$ip = "localhost"
try {
    $ipObj = Get-NetIPAddress -AddressFamily IPv4 | Where-Object {$_.IPAddress -notlike "127.*" -and $_.IPAddress -notlike "169.254.*" -and $_.InterfaceAlias -notlike "*Loopback*"} | Select-Object -First 1
    if ($ipObj) { $ip = $ipObj.IPAddress }
} catch {}

Write-Host ""
Write-Host "=====================================================================" -ForegroundColor Green
Write-Host "  🎉 ติดตั้งระบบบริหารจัดการคลังยาบริจาค สำเร็จเรียบร้อยแล้ว!" -ForegroundColor Green
Write-Host "=====================================================================" -ForegroundColor Green
Write-Host "  📌 Web Application (ห้องยานอก): http://${ip}" -ForegroundColor Yellow
Write-Host "  📌 Backend Swagger Docs:        http://${ip}:${BackendPort}/docs" -ForegroundColor Yellow
Write-Host "  📌 System Health Check:         http://${ip}:${BackendPort}/healthz" -ForegroundColor Yellow
Write-Host ""
Write-Host "  🔐 บัญชีเข้าสู่ระบบ (รหัสผ่าน HOSxP จริงของท่าน):"
Write-Host "     - jaslan : ภก.ยัสลัน มายุดิน (เภสัชกรคลังยาบริจาค)"
Write-Host "     - Ahlam  : อัหลาม แคเม๊าะ (เจ้าพนักงานเภสัชกรรม ตรวจรับ)"
Write-Host "     - dah    : ภญ.วันฮามีดะห์ ปานากาเซ็ง (หัวหน้ากลุ่มงานเภสัชกรรม)"
Write-Host "=====================================================================" -ForegroundColor Green
