# ==============================================================================
# Automated Installer for Donated Medicine Manager (HOSxP Integration)
# Sai Buri Crown Prince Hospital (Code: 10690)
# Compatible with Windows Server / Windows 10 & 11 (PowerShell 5.1 and PS 7+)
# ==============================================================================

param (
    [string]$HosxpHost = "192.168.0.251",
    [string]$HosxpPort = "3306",
    [string]$HosxpUser = "sa",
    [string]$HosxpPassword = "",
    [string]$HosxpDb = "hos",
    [string]$HospitalCode = "10690",
    [string]$HospitalName = "Sai Buri Crown Prince Hospital",
    [int]$FrontendPort = 80,
    [int]$BackendPort = 8000
)

$ErrorActionPreference = "Stop"
$ProjectDir = $PSScriptRoot

function Write-Step([string]$msg) { Write-Host "`n[INSTALL] $msg" -ForegroundColor Cyan }
function Write-OK([string]$msg)   { Write-Host "  + $msg" -ForegroundColor Green }
function Write-Warn([string]$msg) { Write-Host "  ! $msg" -ForegroundColor Yellow }
function Write-Fail([string]$msg) { Write-Host "  X $msg" -ForegroundColor Red; exit 1 }

Write-Host "=====================================================================" -ForegroundColor Green
Write-Host "   Donated Medicine Manager - OPD Pharmacy Server Installer" -ForegroundColor Green
Write-Host "   Sai Buri Crown Prince Hospital (HOSxP Database Integration)" -ForegroundColor Green
Write-Host "=====================================================================" -ForegroundColor Green

# STEP 1: Check Prerequisites
Write-Step "1/8 Checking Prerequisites (Docker and Docker Compose)..."
try { 
    $v = docker --version 2>&1
    Write-OK "Docker: $v" 
} catch { 
    Write-Fail "Docker not found. Please install Docker Desktop from https://www.docker.com" 
}

try { 
    $v = docker compose version 2>&1
    Write-OK "Docker Compose: $v" 
} catch { 
    Write-Fail "Docker Compose not found. Please update Docker Desktop." 
}

try { 
    docker info > $null 2>&1
    Write-OK "Docker daemon is running normally" 
} catch { 
    Write-Fail "Docker daemon is not running. Please start Docker Desktop first." 
}

# STEP 2: Collect Configuration
Write-Step "2/8 HOSxP Database Configuration..."
$inputHost = Read-Host "  HOSxP MySQL Host IP [Default: $HosxpHost]"
if ($inputHost -and $inputHost.Trim()) { $HosxpHost = $inputHost.Trim() }

$inputPort = Read-Host "  HOSxP MySQL Port [Default: $HosxpPort]"
if ($inputPort -and $inputPort.Trim()) { $HosxpPort = $inputPort.Trim() }

$inputUser = Read-Host "  HOSxP MySQL User [Default: $HosxpUser]"
if ($inputUser -and $inputUser.Trim()) { $HosxpUser = $inputUser.Trim() }

if (-not $HosxpPassword) {
    $inputPass = Read-Host "  HOSxP MySQL Password for $HosxpUser [Default: sa]"
    if ($inputPass) { $HosxpPassword = $inputPass } else { $HosxpPassword = "sa" }
}

$inputDb = Read-Host "  Database Name [Default: $HosxpDb]"
if ($inputDb -and $inputDb.Trim()) { $HosxpDb = $inputDb.Trim() }

# STEP 3: Write .env
Write-Step "3/8 Writing .env configuration..."
$envFile = Join-Path $ProjectDir ".env"
$dbUrl = "mysql+pymysql://" + $HosxpUser + ":" + $HosxpPassword + "@" + $HosxpHost + ":" + $HosxpPort + "/" + $HosxpDb
$envContent = @"
# Auto-generated by install.ps1
DATABASE_URL=$dbUrl
HOSXP_HOST=$HosxpHost
HOSXP_PORT=$HosxpPort
HOSXP_USER=$HosxpUser
HOSXP_PASSWORD=$HosxpPassword
HOSXP_DB=$HosxpDb
HOSPITAL_CODE=$HospitalCode
HOSPITAL_NAME=โรงพยาบาลสมเด็จพระยุพราชสายบุรี
FRONTEND_PORT=$FrontendPort
BACKEND_PORT=$BackendPort
"@
[System.IO.File]::WriteAllText($envFile, $envContent, [System.Text.Encoding]::UTF8)
Write-OK ".env written successfully"

# STEP 4: Write secrets.toml
Write-Step "4/8 Writing secrets.toml..."
$secretsFile = Join-Path $ProjectDir "secrets.toml"
$secretsContent = @"
# Auto-generated by install.ps1
[database]
host = "$HosxpHost"
port = $HosxpPort
name = "$HosxpDb"
user = "$HosxpUser"
password = "$HosxpPassword"
driver = "mysql+pymysql"
url = "$dbUrl"

[system]
hospital_name = "โรงพยาบาลสมเด็จพระยุพราชสายบุรี"
hospital_code = "$HospitalCode"
environment = "production"
"@
[System.IO.File]::WriteAllText($secretsFile, $secretsContent, [System.Text.Encoding]::UTF8)
Write-OK "secrets.toml written successfully"

# STEP 5: Build images
Write-Step "5/8 Building Docker Images (backend and frontend)..."
Set-Location $ProjectDir
docker compose build
Write-OK "Docker images built successfully"

# STEP 6: Start services
Write-Step "6/8 Starting Docker Containers..."
docker compose up -d
Write-OK "Containers started successfully"

# STEP 7: Verify health
Write-Step "7/8 Verifying Service Health..."
Start-Sleep 8
try {
    $h = Invoke-RestMethod "http://localhost:${BackendPort}/healthz" -TimeoutSec 15
    Write-OK "Backend API Health: $($h.status)"
    $r = Invoke-RestMethod "http://localhost:${BackendPort}/readyz" -TimeoutSec 15
    Write-OK "Database Connection: $($r.database)"
} catch { 
    Write-Warn "System is starting up or connecting to HOSxP MySQL..." 
}

# STEP 8: Firewall & Auto-start setup
Write-Step "8/8 Configuring Windows Defender Firewall..."
try {
    New-NetFirewallRule -DisplayName "Donated-Medicine-Web-$FrontendPort" -Direction Inbound -Protocol TCP -LocalPort $FrontendPort -Action Allow -EA SilentlyContinue | Out-Null
    New-NetFirewallRule -DisplayName "Donated-Medicine-API-$BackendPort" -Direction Inbound -Protocol TCP -LocalPort $BackendPort -Action Allow -EA SilentlyContinue | Out-Null
    Write-OK "Firewall ports $FrontendPort (Web) and $BackendPort (API) opened successfully"
} catch {
    Write-Warn "Could not add firewall rule automatically. Run PowerShell as Administrator if needed."
}

# Get Local IP
$ip = "localhost"
try {
    $ipObj = Get-NetIPAddress -AddressFamily IPv4 | Where-Object {$_.IPAddress -notlike "127.*" -and $_.IPAddress -notlike "169.254.*" -and $_.InterfaceAlias -notlike "*Loopback*"} | Select-Object -First 1
    if ($ipObj) { $ip = $ipObj.IPAddress }
} catch {}

Write-Host ""
Write-Host "=====================================================================" -ForegroundColor Green
Write-Host "  Installation Completed Successfully!" -ForegroundColor Green
Write-Host "=====================================================================" -ForegroundColor Green
Write-Host "  Web Application (OPD Pharmacy): http://${ip}" -ForegroundColor Yellow
Write-Host "  Backend Swagger Docs:           http://${ip}:${BackendPort}/docs" -ForegroundColor Yellow
Write-Host "  System Health Check:            http://${ip}:${BackendPort}/healthz" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Login Credentials (use your HOSxP account):"
Write-Host "     - jaslan : ภก.ยัสลัน มายุดิน (เภสัชกรคลังยาบริจาค)"
Write-Host "     - Ahlam  : อัหลาม แคเม๊าะ (เจ้าพนักงานเภสัชกรรม ตรวจรับ)"
Write-Host "     - dah    : ภญ.วันฮามีดะห์ ปานากาเซ็ง (หัวหน้ากลุ่มงานเภสัชกรรม)"
Write-Host "=====================================================================" -ForegroundColor Green
